# Generated by Django 3.2.9 on 2021-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_titles_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='titles',
            name='text',
            field=models.TextField(),
        ),
    ]
