# Generated by Django 3.2.9 on 2021-11-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20211102_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name_plural': 'titles'},
        ),
    ]
