# Generated by Django 3.2.9 on 2021-11-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_titles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.titles')),
            ],
            options={
                'verbose_name_plural': 'discussions',
            },
        ),
    ]
