# Generated by Django 3.2.9 on 2021-11-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
